#!/bin/bash
# rock_pi4_pios

sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
sudo apt install net-tools network-manager build-essential cmake make gcc python3-dev jupyter-notebook libatlas-base-dev
sudo apt install ranger zsh curl git vim vim-gtk3 fzf htop xcape tmux ctags neofetch python-pip zip unzip nodejs yarn blueman

sudo apt install xorg i3 
sudo apt install chromium xfce4-terminal nautilus w3m lxappearance scrot compton feh rofi --fix-missing
sudo apt install fonts-dejavu fonts-firacode

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
chsh -s $(which zsh) # change default shell as zsh

# oh my zsh plugins, will be called in .zshrc in dotfiles
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# apply rock setup immediately after this and reboot

mkdir -p ~/.config/autostart
cp ./remap/xmodmap/xmodmap.desktop ~/.config/autostart

