:autocmd InsertEnter * set cul
:autocmd InsertLeave * set nocul

syntax enable
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4

set expandtab
set smartindent
set autoindent

set hidden
set nobackup
set noswapfile
set nowritebackup
set nocompatible
set undofile
set undodir=~/.vim/undodir
set undofile
set incsearch
set colorcolumn=80

set cmdheight=1
set runtimepath+=~/.vim_runtime
set encoding=utf-8
set viminfo='20
set modifiable

set number relativenumber
set nonumber norelativenumber " turn hybrid line numbers off
set number! relativenumber!   " toggle hybrid line numbers

set foldmethod=indent
set foldlevel=99
set cursorline
set showmatch

" split bar char fill
set fillchars+=vert:\ 

" share clipboard with system
set clipboard=unnamedplus
" set foldmethod=marker

" NERDTree setups
nmap nt :NERDTreeToggle<CR>
let NERDTreeWinSize=30
let NERDTreeShowHidden=1

" Tlist setups
nmap tl :TlistToggle<CR>
let Tlist_WinWidth=30
let Tlist_Use_Right_Window=0
let Tlist_Auto_Update=1
let Tlist_File_Fold_Auto_Close=1
let Tlist_Exit_OnlyWindow=1

" WinManager setups
nmap wm :WMToggle<CR>
let g:winManagerWidth=30

" http://wuyudong.com/2015/12/29/1635.html
" additional actions required in ~/.vim/plugin/winmanager.vim
" add <exe 'q'> after <call s:StartWindowsManager()> 
"   in func ToggleWindowsManager 
let g:NERDTree_title="[NERDTree]"
let g:winManagerWindowLayout="NERDTree|TagList"
function! NERDTree_Start()
    exec 'NERDTree'
endfunction
function! NERDTree_IsValid()
    return 1
endfunction
nmap wm :WMToggle<CR>

" gruvbox dark
autocmd vimenter * colorscheme gruvbox
set bg=dark

" leader key remap
let mapleader = "\<space>"

nnoremap <leader>q :q<CR>
nnoremap <leader>/ :set hlsearch!<CR>

" Remap Escape to quit terminal normal
" https://github.com/vim/vim/issues/2216
tnoremap <Esc> <C-\><C-N> 
nnoremap <leader>t :terminal<CR>
nnoremap <leader>v :vertical terminal<CR>

" buffertabs, deprecated, installed with airline
" nnoremap <leader>n :bnext<CR>
nnoremap <leader>[ <C-b>
nnoremap <leader>] <C-f>

" Elegant splitting
nnoremap <leader><Tab> <C-W><C-W>
nnoremap <leader>j <C-W><C-j>
nnoremap <leader>k <C-W><C-k>
nnoremap <leader>l <C-W><C-l>
nnoremap <leader>h <C-W><C-h>
nnoremap <leader>J <C-W>J
nnoremap <leader>K <C-W>K
nnoremap <leader>L <C-W>L
nnoremap <leader>H <C-W>H

nnoremap <leader>o :browse oldfiles<CR>
nnoremap <leader>u :UndotreeShow<CR>
nnoremap <leader>gd :YouCompleter GoTo<CR>

" nnoremap <C-J> <C-W><C-J>
" nnoremap <C-K> <C-W><C-K>
" nnoremap <C-L> <C-W><C-L>
" nnoremap <C-H> <C-W><C-H>

nnoremap <leader>s :split<CR>
nnoremap <leader>a :vsplit<CR>

nmap <leader>= :vertical resize +5<CR>
nmap <leader>- :vertical resize -5<CR>
nmap <leader>, :res -5<CR>
nmap <leader>. :res +5<CR>
filetype on " ON for TagList

inoremap <expr> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>" 


" VUNDLE PLUGIN SECTION "
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

Plugin 'ThePrimeagen/vim-be-good', {'do': './install.sh'}
Plugin 'ycm-core/YouCompleteMe'
Plugin 'mbbill/undotree'

Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plugin 'junegunn/fzf.vim'
Plugin 'jpalardy/vim-slime'
Plugin 'hanschen/vim-ipython-cell'

Plugin 'google/vim-maktaba'
Plugin 'google/vim-codefmt'
Plugin 'google/vim-glaive'

Plugin 'chrisbra/csv.vim'
Plugin 'morhetz/gruvbox'

Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-commentary'

Plugin 'VundleVim/Vundle.vim'
Plugin 'yegappan/taglist', {'rtp': 'vim/'}

Plugin 'sonph/onehalf', {'rtp': 'vim/'}
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" let g:airline_theme='onehalfdark' " third-party scheme
let g:airline_theme='raven' " official airline scheme
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#left_sep=' '
" 'deus', 'angr', 'atomic', 'bubblegum', 'molokai', 'raven'

" NERDTree
Plugin 'preservim/nerdtree'
let NERDTreeShowLineNumbers=1
autocmd FileType nerdtree setlocal relativenumber
" extra colorscheme
" Plugin 'tiagofumo/vim-nerdtree-syntax-highlight'

" Pandoc Family
" Plugin 'vim-pandoc/vim-pandoc'
" Plugin 'vim-pandoc/vim-pandoc-syntax'
" let g:pandoc#modules#disabled = ["spell"]

let python_highlight_all=1

call vundle#end()

" filetype plugin indent on
" To ignore plugin indent changes, instead use:
filetype plugin on
